In [60]:
"""1.init weight matrix
    2. loop through epoch times
    3. inner loop loops through 32 animals and calculate the distance between animal row and the rows in weight matrix
    4. the row with smallest distance wins and it and its neighbours gets an update.
    5. make the neighbourhood smaller"""

from __future__ import division

import numpy as np
from matplotlib import pyplot as plt
from matplotlib import patches as patches

n_neurons = 100
d = 80
epochs = 20#20 epochs
eta  = 0.2
num_of_neighbours = 50
#use a weight matrix 100x84 init with random number 0 <r<1
w = np.random.rand(100, 84)

animals = np.genfromtxt('data_lab2/animals.dat',delimiter =',')
print(animals.shape)

f = open('data_lab2/animalnames.txt', "r")
animal_names = f.readlines()
f.close()
print(animal_names)
x = animals.reshape((32,84))
print(x)
print(w)
for n in range(epochs):
    for j, row in enumerate(x):
        #print(row)
        hmm = w - row
        #print(hmm)
        min_dist = 100000
        index_of_min = 0
        for i,weight_row in enumerate(hmm):
            #print(weight_row)
            distance = np.linalg.norm(weight_row)
            
            
            if distance < min_dist:
                #print(min_dist)
                min_dist = distance
                index_of_min = i
        #print(w[index_of_min,:] + eta*(w[index_of_min,:]-row))
        #update weights- always update the actual row
        w[index_of_min,:] = w[index_of_min,:] + eta*(w[index_of_min,:]-row)
        #And for num_of_neighbours update the rest.
        for i in range(-int(num_of_neighbours/2),int(num_of_neighbours/2)):
            if int(index_of_min+i) >=w.shape[0]:
                #index = w.shape[0]%int(index_of_min+i)-1
                #w[index,:] = w[index,:] + eta*(row-w[index,:])
                continue
            elif int(index_of_min+i) <0:
                continue
            else:
                w[index_of_min+i,:] = w[index_of_min+i,:] + eta*(row-w[index_of_min+i,:])
                
    if num_of_neighbours <= 2:
        num_of_neighbours = 0
    else:
        num_of_neighbours += -4
    print(num_of_neighbours)
print(w)
#print the animals
winners = np.zeros(32)
for j,row in enumerate(x):
    hmm = row-w
    min_dist = 100000
    index_of_min = 0
    for i,weight_row in enumerate(hmm):
        distance = np.linalg.norm(weight_row)
        #print(i)

        if distance < min_dist:
            min_dist = distance
            index_of_min = i
            #print(min_dist)
            
          
    winners[j] = index_of_min

#final_animal_list = np.sort(winners)
print(final_animal_list)
Z = [i for _,i in sorted(zip(winners,animal_names))]
np.transpose(Z)


(2688,)
["'antelop'\t\n", "'ape'\t\n", "'bat'\t\n", "'bear'\t\n", "'beetle'\t\n", "'butterfly'\t\n", "'camel'\t\n", "'cat'\t\n", "'crocodile'\t\n", "'dog'\t\n", "'dragonfly'\t\n", "'duck'\t\n", "'elephant'\t\n", "'frog'\t\n", "'giraffe'\t\n", "'grasshopper'\t\n", "'horse'\n", "'housefly'\n", "'hyena'\t\n", "'kangaroo'\t\n", "'lion'\t\n", "'moskito'\t\n", "'ostrich'\t\n", "'pelican'\t\n", "'penguin'\t\n", "'pig'\t\n", "'rabbit'\t\n", "'rat'\t\n", "'seaturtle'\t\n", "'skunk'\t\n", "'spider'\t\n", "'walrus'"]
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.79162972 0.55195494 0.0575828  ... 0.33632558 0.4712649  0.27465771]
 [0.20825363 0.65475028 0.6226459  ... 0.01488468 0.18197894 0.78542901]
 [0.46030932 0.95405358 0.86548821 ... 0.86281344 0.64640047 0.56007622]
 ...
 [0.20773973 0.50509638 0.42391064 ... 0.82393208 0.32912986 0.17695193]
 [0.85844269 0.89541649 0.46536398 

array(["'housefly'\n", "'moskito'\t\n", "'spider'\t\n", "'beetle'\t\n",
       "'butterfly'\t\n", "'dragonfly'\t\n", "'grasshopper'\t\n",
       "'pelican'\t\n", "'duck'\t\n", "'penguin'\t\n", "'ostrich'\t\n",
       "'crocodile'\t\n", "'seaturtle'\t\n", "'frog'\t\n", "'walrus'",
       "'ape'\t\n", "'hyena'\t\n", "'bear'\t\n", "'dog'\t\n", "'cat'\t\n",
       "'bat'\t\n", "'lion'\t\n", "'rabbit'\t\n", "'rat'\t\n",
       "'elephant'\t\n", "'skunk'\t\n", "'kangaroo'\t\n", "'giraffe'\t\n",
       "'antelop'\t\n", "'camel'\t\n", "'horse'\n", "'pig'\t\n"],
      dtype='<U15')