In [6]:
import numpy as np
import itertools

In [7]:
def update_weights(X,W):
    for x in X:
        W += np.outer(x,x)
    for i in range(W.shape[0]):
        W[i,i] = 0
    return W

def recall(x,W):
    
    x = x.reshape((-1,1))
    #print(x)
    #print(W.shape)
    #x = np.sign(np.matmul(W.T,x))
    
    for i in range(x.shape[0]):
        x[i] = np.sign(np.dot(x.T,W[i,:]))
    return x

def find_pattern(x, W, epochs):
    for i in range(epochs):
        x = recall(x,W)
    return x



# 3.1.1

In [8]:

x1=np.array((-1,-1, 1,-1, 1,-1,-1, 1))
#print(np.outer(x1,x1))
x2=np.array((-1, -1, -1, -1, -1, 1, -1, -1))
x3=np.array((-1, 1, 1,-1,-1, 1,-1, 1))

W = np.zeros((x1.shape[0],x1.shape[0]))
print(W.shape)
X = np.vstack((x1,x2,x3))
print(update_weights(X,W))

x1d=np.array((1,-1, 1,-1, 1,-1,-1, 1,))
x2d=np.array((1, 1,-1,-1,-1, 1,-1,-1,))
x3d=np.array((1,1,1,-1,1,1,-1,1))
epochs = 3

print("True x1",x1)
#print("Recalled x1",recall(x1,W))
print("Distorded x1",x1d)
print("Recalled x1",find_pattern(x1d,W,epochs))
print("True x2",x2)
print("Distorded x2",x2d)
print("Recalled x2",find_pattern(x2d,W,epochs))
#print("Recalled x2",recall(x2,W))

print("True x3",x3)
#print("Recalled x3",recall(x3,W))
print("Distorded x3",x3d)
print("Recalled x3",find_pattern(x3d,W,epochs))

(8, 8)
[[ 0.  1. -1.  3.  1. -1.  3. -1.]
 [ 1.  0.  1.  1. -1.  1.  1.  1.]
 [-1.  1.  0. -1.  1. -1. -1.  3.]
 [ 3.  1. -1.  0.  1. -1.  3. -1.]
 [ 1. -1.  1.  1.  0. -3.  1.  1.]
 [-1.  1. -1. -1. -3.  0. -1. -1.]
 [ 3.  1. -1.  3.  1. -1.  0. -1.]
 [-1.  1.  3. -1.  1. -1. -1.  0.]]
True x1 [-1 -1  1 -1  1 -1 -1  1]
Distorded x1 [ 1 -1  1 -1  1 -1 -1  1]
Recalled x1 [[-1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [-1]
 [ 1]]
True x2 [-1 -1 -1 -1 -1  1 -1 -1]
Distorded x2 [ 1  1 -1 -1 -1  1 -1 -1]
Recalled x2 [[-1]
 [-1]
 [-1]
 [-1]
 [-1]
 [ 1]
 [-1]
 [-1]]
True x3 [-1  1  1 -1 -1  1 -1  1]
Distorded x3 [ 1  1  1 -1  1  1 -1  1]
Recalled x3 [[-1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [-1]
 [ 1]]


# 3.1.2

In [70]:
def generate_input_vectors():
    
    X = np.zeros((8,0))
    x = np.ones((8,1))
    X = np.append(X,x,axis=1)
    #X = np.append(X,-x,axis=1)
    for bias in range (x.shape[0]):
        x = np.ones((8,1))
        for i in range(x.shape[0]-bias):
            x[bias+i] = -x[bias+i]
            print(x)
            X = np.append(X,x,axis=1)
    for i in range(1,x.shape[0]):
        x = -np.ones((8,1))
        x[i] = 1
        x[i] = 1
        X = np.append(X,x,axis=1)
        
    for i in range(0,x.shape[0]-1):
        x = -np.ones((8,1))
        x[i] = 1
        x[i+1] = 1
    
        X = np.append(X,x,axis=1)
        
    for i in range(0,x.shape[0]-2):
        x = -np.ones((8,1))
        x[i] = 1
        x[i+1] = 1
        x[i+2] = 1
        print(x)
        X = np.append(X,x,axis=1)
    #print(X)
    return X

def run_network(X,W,epochs):
    saved_patterns = np.array((8,1))
    
    for i,column in enumerate(X.T):
        #print(column)
        x = find_pattern(column,W,epochs)
        exists = False
        #print(x)
        if i == 0:
            x = x.reshape((-1,1))
            saved_patterns = x
            #print(saved_patterns)
        else:
            for saved_column in saved_patterns.T:
                #print("saved_column",saved_column)
                saved_column = saved_column.reshape((-1,1))
                #print(saved_column - x)
                #print((saved_column - x).any())
                if (saved_column - x).any() == False:
                    exists = True
            if exists != True:
                print("saving pattern")
                x = x.reshape((-1,1))
                print(saved_patterns.shape)
                saved_patterns = np.append(saved_patterns,x,axis=1)
                print(saved_patterns.shape)
    print(saved_patterns)
    return saved_patterns

epochs = 10
x1=np.array((-1,-1, 1,-1, 1,-1,-1, 1))
#print(np.outer(x1,x1))
x2=np.array((-1, -1, -1, -1, -1, 1, -1, -1))
x3=np.array((-1, 1, 1,-1,-1, 1,-1, 1))

W = np.zeros((x1.shape[0],x1.shape[0]))
print(W.shape)
X = np.vstack((x1,x2,x3))
print(update_weights(X,W))
X = generate_input_vectors()
X = np.array(X)
#X = X.reshape((8,256))
print(X.shape)
#print(X[:,0:10])
X = np.unique(X,axis=1)
print(X.shape)
print(X)
s = run_network(X,W,epochs)
print(s.shape)
print(s[:,1])
print(s[:,2])

(8, 8)
[[ 0.  1. -1.  3.  1. -1.  3. -1.]
 [ 1.  0.  1.  1. -1.  1.  1.  1.]
 [-1.  1.  0. -1.  1. -1. -1.  3.]
 [ 3.  1. -1.  0.  1. -1.  3. -1.]
 [ 1. -1.  1.  1.  0. -3.  1.  1.]
 [-1.  1. -1. -1. -3.  0. -1. -1.]
 [ 3.  1. -1.  3.  1. -1.  0. -1.]
 [-1.  1.  3. -1.  1. -1. -1.  0.]]
[[-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]]
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]]
[[-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]]
[[ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[ 1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[ 1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]]
[[ 1.]
 [-1.]
 [-1.]
 [-1.]


In [37]:
def generate_input_vectors_test(n):
    out = np.zeros((8,256))
    for i in range(1<<n):
        s=bin(i)[2:]
        s='0'*(n-len(s))+s
        s = list(s)
        s = np.array(s,dtype=np.int32)
        out[:,i] = s.T
    z_ind = np.argwhere(out == 0)
    for ind in z_ind:
        out[ind[0],ind[1]] = -1
    return out
input_patterns = generate_input_vectors_test(8)


print(input_patterns.shape)
X = np.unique(input_patterns,axis=1)
print(X.shape)


(8, 256)
(8, 256)
